[tool.kedro]
package_name = "premium_client_churn"
project_name = "Premium Client Churn"
project_version = "0.17.4"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 88
known_third_party = "kedro"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/premium_client_churn -ra"""
