# Parameters for the pipelines

data_engineering:
  target_class: BAJA+2
  bool_to_cat:
    - active_quarter
    - cliente_vip
    - internet
    - tpaquete2
    - tpaquete3
    - tcuentas
    - tcallcenter
    - thomebanking
    - Master_delinquency
    - Visa_delinquency
    - clase_ternaria
  day_to_year:
    - Master_Fvencimiento
    - Master_Finiciomora
    - Master_fultimo_cierre
    - Master_fechaalta
    - Visa_Fvencimiento
    - Visa_Finiciomora
    - Visa_fultimo_cierre
    - Visa_fechaalta
  # month_to_year: cliente_antiguedad

experiment_dates:
  train_from: 201709
  train_to: 201908
  valid: 201910
  test: 201912
  to_leader: 202002
