# Parameters for the pipelines

data_engineering:
  target_class: BAJA+2
  lag_qty: 3
  bool_to_cat:
    - active_quarter
    - cliente_vip
    - internet
    - tpaquete2
    - tpaquete3
    - tcuentas
    - tcallcenter
    - thomebanking
    - Master_delinquency
    - Visa_delinquency
    - clase_ternaria
  day_to_year:
    - Master_Fvencimiento
    - Master_Finiciomora
    - Master_fultimo_cierre
    - Master_fechaalta
    - Visa_Fvencimiento
    - Visa_Finiciomora
    - Visa_fultimo_cierre
    - Visa_fechaalta
  cols_pesos:
    - mrentabilidad
    - mrentabilidad_annual
    - mcomisiones
    - mactivos_margen
    - mpasivos_margen
    - mcuenta_corriente_adicional
    - mcuenta_corriente
    - mcaja_ahorro
    - mcaja_ahorro_adicional
    - mdescubierto_preacordado
    - mcuentas_saldo
    - mautoservicio
    - mtarjeta_visa_consumo
    - mtarjeta_master_consumo
    - mprestamos_personales
    - mprestamos_prendarios
    - mprestamos_hipotecarios
    - mplazo_fijo_pesos
    - minversion1_pesos
    - minversion2
    - mpayroll
    - mpayroll2
    - mcuenta_debitos_automaticos
    - mttarjeta_visa_debitos_automaticos
    - mttarjeta_master_debitos_automaticos
    - mpagodeservicios
    - mpagomiscuentas
    - mcajeros_propios_descuentos
    - mtarjeta_visa_descuentos
    - mtarjeta_master_descuentos
    - mcomisiones_mantenimiento
    - mcomisiones_otras
    - mforex_buy
    - mforex_sell
    - mtransferencias_recibidas
    - mtransferencias_emitidas
    - mextraccion_autoservicio
    - mcheques_depositados
    - mcheques_emitidos
    - mcheques_depositados_rechazados
    - mcheques_emitidos_rechazados
    - matm
    - matm_other
    - Master_mfinanciacion_limite
    - Master_msaldototal
    - Master_msaldopesos
    - Master_mconsumospesos
    - Master_mlimitecompra
    - Master_madelantopesos
    - Master_mpagado
    - Master_mpagospesos
    - Master_mconsumototal
    - Master_mpagominimo
    - Visa_mfinanciacion_limite
    - Visa_msaldototal
    - Visa_msaldopesos
    - Visa_mconsumospesos
    - Visa_mlimitecompra
    - Visa_madelantopesos
    - Visa_mpagado
    - Visa_mpagospesos
    - Visa_mconsumototal
    - Visa_mpagominimo
  cols_to_lag:
    - mrentabilidad
    - mrentabilidad_annual
    - mcomisiones
    - mactivos_margen
    - mpasivos_margen
    - cproductos
    - ccuenta_corriente
    - mcuenta_corriente_adicional
    - mcuenta_corriente
    - ccaja_ahorro
    - mcaja_ahorro
    - mcaja_ahorro_adicional
    - mcaja_ahorro_dolares
    - mdescubierto_preacordado
    - mcuentas_saldo
    - ctarjeta_debito
    - ctarjeta_debito_transacciones
    - mautoservicio
    - ctarjeta_visa
    - ctarjeta_visa_transacciones
    - mtarjeta_visa_consumo
    - ctarjeta_master
    - ctarjeta_master_transacciones
    - mtarjeta_master_consumo
    - cprestamos_personales
    - mprestamos_personales
    - cprestamos_prendarios
    - mprestamos_prendarios
    - cprestamos_hipotecarios
    - mprestamos_hipotecarios
    - cplazo_fijo
    - mplazo_fijo_dolares
    - mplazo_fijo_pesos
    - cinversion1
    - minversion1_pesos
    - minversion1_dolares
    - cinversion2
    - minversion2
    - cseguro_vida
    - cseguro_auto
    - cseguro_vivienda
    - cseguro_accidentes_personales
    - ccaja_seguridad
    - cpayroll_trx
    - mpayroll
    - mpayroll2
    - cpayroll2_trx
    - ccuenta_debitos_automaticos
    - mcuenta_debitos_automaticos
    - ctarjeta_visa_debitos_automaticos
    - mttarjeta_visa_debitos_automaticos
    - ctarjeta_master_debitos_automaticos
    - mttarjeta_master_debitos_automaticos
    - cpagodeservicios
    - mpagodeservicios
    - cpagomiscuentas
    - mpagomiscuentas
    - ccajeros_propios_descuentos
    - mcajeros_propios_descuentos
    - ctarjeta_visa_descuentos
    - mtarjeta_visa_descuentos
    - ctarjeta_master_descuentos
    - mtarjeta_master_descuentos
    - ccomisiones_mantenimiento
    - mcomisiones_mantenimiento
    - ccomisiones_otras
    - mcomisiones_otras
    - cforex
    - cforex_buy
    - mforex_buy
    - cforex_sell
    - mforex_sell
    - ctransferencias_recibidas
    - mtransferencias_recibidas
    - ctransferencias_emitidas
    - mtransferencias_emitidas
    - cextraccion_autoservicio
    - mextraccion_autoservicio
    - ccheques_depositados
    - mcheques_depositados
    - ccheques_emitidos
    - mcheques_emitidos
    - ccheques_depositados_rechazados
    - mcheques_depositados_rechazados
    - ccheques_emitidos_rechazados
    - mcheques_emitidos_rechazados
    - ccallcenter_transacciones
    - chomebanking_transacciones
    - ccajas_transacciones
    - ccajas_consultas
    - ccajas_depositos
    - ccajas_extracciones
    - ccajas_otras
    - catm_trx
    - matm
    - catm_trx_other
    - matm_other
    - ctrx_quarter
    - Master_status
    - Master_mfinanciacion_limite
    - Master_msaldototal
    - Master_msaldopesos
    - Master_msaldodolares
    - Master_mconsumospesos
    - Master_mconsumosdolares
    - Master_mlimitecompra
    - Master_madelantopesos
    - Master_madelantodolares
    - Master_mpagado
    - Master_mpagospesos
    - Master_mpagosdolares
    - Master_mconsumototal
    - Master_cconsumos
    - Master_cadelantosefectivo
    - Master_mpagominimo
    - Visa_status
    - Visa_mfinanciacion_limite
    - Visa_msaldototal
    - Visa_msaldopesos
    - Visa_msaldodolares
    - Visa_mconsumospesos
    - Visa_mconsumosdolares
    - Visa_mlimitecompra
    - Visa_madelantopesos
    - Visa_madelantodolares
    - Visa_mpagado
    - Visa_mpagospesos
    - Visa_mpagosdolares
    - Visa_mconsumototal
    - Visa_cconsumos
    - Visa_cadelantosefectivo
    - Visa_mpagominimo

data_science:
  experiment_dates:
    train: 201909
    valid: 201911
    test: 201912
    leader: 202002
  months_to_train:
    - 12
  cols_to_drop:
    - numero_de_cliente
    - foto_mes
    - clase_ternaria
  target_class: clase_ternaria
  optim:
    with_optim: True
    seed: 1234
  model_fixed:
    deterministic: True
    early_stopping_rounds: 550
    force_col_wise: True
    learning_rate: 0.01
    max_bin: 32
    metric: auc
    n_estimators: 5000
    objective: binary
    verbose: -1
  model_optimized:
    cosito: 123
