# Parameters for the pipelines

data_engineering:
  target_class: BAJA+2
  
  lag_qty: 3
  
  bool_to_cat:
    - active_quarter
    - clase_ternaria
    - cliente_vip
    - internet
    - Master_delinquency
    - tcallcenter
    - tcuentas
    - thomebanking
    - tpaquete2
    - tpaquete3
    - Visa_delinquency
  
  day_to_year:
    - Master_fechaalta
    - Master_Finiciomora
    - Master_fultimo_cierre
    - Master_Fvencimiento
    - Visa_fechaalta
    - Visa_Finiciomora
    - Visa_fultimo_cierre
    - Visa_Fvencimiento
  
  cols_pesos:
    - mactivos_margen
    - Master_madelantopesos
    - Master_mconsumospesos
    - Master_mconsumototal
    - Master_mfinanciacion_limite
    - Master_mlimitecompra
    - Master_mpagado
    - Master_mpagominimo
    - Master_mpagospesos
    - Master_msaldopesos
    - Master_msaldototal
    - matm
    - matm_other
    - mautoservicio
    - mcaja_ahorro
    - mcaja_ahorro_adicional
    - mcajeros_propios_descuentos
    - mcheques_depositados
    - mcheques_depositados_rechazados
    - mcheques_emitidos
    - mcheques_emitidos_rechazados
    - mcomisiones
    - mcomisiones_mantenimiento
    - mcomisiones_otras
    - mcuenta_corriente
    - mcuenta_corriente_adicional
    - mcuenta_debitos_automaticos
    - mcuentas_saldo
    - mdescubierto_preacordado
    - mextraccion_autoservicio
    - mforex_buy
    - mforex_sell
    - minversion1_pesos
    - minversion2
    - mpagodeservicios
    - mpagomiscuentas
    - mpasivos_margen
    - mpayroll
    - mpayroll2
    - mplazo_fijo_pesos
    - mprestamos_hipotecarios
    - mprestamos_personales
    - mprestamos_prendarios
    - mrentabilidad
    - mrentabilidad_annual
    - mtarjeta_master_consumo
    - mtarjeta_master_descuentos
    - mtarjeta_visa_consumo
    - mtarjeta_visa_descuentos
    - mtransferencias_emitidas
    - mtransferencias_recibidas
    - mttarjeta_master_debitos_automaticos
    - mttarjeta_visa_debitos_automaticos
    - Visa_madelantopesos
    - Visa_mconsumospesos
    - Visa_mconsumototal
    - Visa_mfinanciacion_limite
    - Visa_mlimitecompra
    - Visa_mpagado
    - Visa_mpagominimo
    - Visa_mpagospesos
    - Visa_msaldopesos
    - Visa_msaldototal
  
  cols_to_lag:
    - catm_trx
    - catm_trx_other
    - ccaja_ahorro
    - ccaja_seguridad
    - ccajas_consultas
    - ccajas_depositos
    - ccajas_extracciones
    - ccajas_otras
    - ccajas_transacciones
    - ccajeros_propios_descuentos
    - ccallcenter_transacciones
    - ccheques_depositados
    - ccheques_depositados_rechazados
    - ccheques_emitidos
    - ccheques_emitidos_rechazados
    - ccomisiones_mantenimiento
    - ccomisiones_otras
    - ccuenta_corriente
    - ccuenta_debitos_automaticos
    - cextraccion_autoservicio
    - cforex
    - cforex_buy
    - cforex_sell
    - chomebanking_transacciones
    - cinversion1
    - cinversion2
    - cpagodeservicios
    - cpagomiscuentas
    - cpayroll_trx
    - cpayroll2_trx
    - cplazo_fijo
    - cprestamos_hipotecarios
    - cprestamos_personales
    - cprestamos_prendarios
    - cproductos
    - cseguro_accidentes_personales
    - cseguro_auto
    - cseguro_vida
    - cseguro_vivienda
    - ctarjeta_debito
    - ctarjeta_debito_transacciones
    - ctarjeta_master
    - ctarjeta_master_debitos_automaticos
    - ctarjeta_master_descuentos
    - ctarjeta_master_transacciones
    - ctarjeta_visa
    - ctarjeta_visa_debitos_automaticos
    - ctarjeta_visa_descuentos
    - ctarjeta_visa_transacciones
    - ctransferencias_emitidas
    - ctransferencias_recibidas
    - ctrx_quarter
    - mactivos_margen
    - Master_cadelantosefectivo
    - Master_cconsumos
    - Master_madelantodolares
    - Master_madelantopesos
    - Master_mconsumosdolares
    - Master_mconsumospesos
    - Master_mconsumototal
    - Master_mfinanciacion_limite
    - Master_mlimitecompra
    - Master_mpagado
    - Master_mpagominimo
    - Master_mpagosdolares
    - Master_mpagospesos
    - Master_msaldodolares
    - Master_msaldopesos
    - Master_msaldototal
    - Master_status
    - matm
    - matm_other
    - mautoservicio
    - mcaja_ahorro
    - mcaja_ahorro_adicional
    - mcaja_ahorro_dolares
    - mcajeros_propios_descuentos
    - mcheques_depositados
    - mcheques_depositados_rechazados
    - mcheques_emitidos
    - mcheques_emitidos_rechazados
    - mcomisiones
    - mcomisiones_mantenimiento
    - mcomisiones_otras
    - mcuenta_corriente
    - mcuenta_corriente_adicional
    - mcuenta_debitos_automaticos
    - mcuentas_saldo
    - mdescubierto_preacordado
    - mextraccion_autoservicio
    - mforex_buy
    - mforex_sell
    - minversion1_dolares
    - minversion1_pesos
    - minversion2
    - mpagodeservicios
    - mpagomiscuentas
    - mpasivos_margen
    - mpayroll
    - mpayroll2
    - mplazo_fijo_dolares
    - mplazo_fijo_pesos
    - mprestamos_hipotecarios
    - mprestamos_personales
    - mprestamos_prendarios
    - mrentabilidad
    - mrentabilidad_annual
    - mtarjeta_master_consumo
    - mtarjeta_master_descuentos
    - mtarjeta_visa_consumo
    - mtarjeta_visa_descuentos
    - mtransferencias_emitidas
    - mtransferencias_recibidas
    - mttarjeta_master_debitos_automaticos
    - mttarjeta_visa_debitos_automaticos
    - Visa_cadelantosefectivo
    - Visa_cconsumos
    - Visa_madelantodolares
    - Visa_madelantopesos
    - Visa_mconsumosdolares
    - Visa_mconsumospesos
    - Visa_mconsumototal
    - Visa_mfinanciacion_limite
    - Visa_mlimitecompra
    - Visa_mpagado
    - Visa_mpagominimo
    - Visa_mpagosdolares
    - Visa_mpagospesos
    - Visa_msaldodolares
    - Visa_msaldopesos
    - Visa_msaldototal
    - Visa_status
data_science:
  experiment_dates:
    train: 201909
    valid: 201911
    test: 201912
    leader: 202002
  
  months_to_train: 1
  
  cols_to_drop:
    - clase_ternaria
    - foto_mes
    - numero_de_cliente
  
  target_class: clase_ternaria
  
  optim:
    with_optim: False
    seed: 1234
  
  model_fixed:
    deterministic: True
    early_stopping_rounds: 550
    force_col_wise: True
    learning_rate: 0.01
    max_bin: 32
    metric: auc
    n_estimators: 5000
    objective: binary
    verbose: -1
  
  model_optimized:
    bagging_fraction: 0.6221504528746072
    bagging_freq: 4
    feature_fraction: 0.4
    lambda_l1: 0.0016166420446036664
    lambda_l2: 8.12561926830844
    min_child_samples: 100
    n_estimators: 1041
    num_leaves: 72
  
  pcutoff:
    TP_gain: 29250
    FP_gain: -750
